### ISSUE TITLE
ModuleNotFoundError: No module named 'pymem'

### ISSUE THREAD

**Issue by WeaselOnaStick** [WeaselOnaStick/map-data-editor#2]
Some people have been reporting this bug that I hope to fix soon. (Only idea I have is to separate this module into a separate add-on)
![image](https://user-images.githubusercontent.com/10953814/130883088-ed57a4d6-7222-4b11-95fb-3acc838c17ce.png)
For now you can either use release version before 2.1.5 or try following fix:

1. Manually download [pymem from pypi.org here https://pypi.org/project/Pymem/#files](https://pypi.org/project/Pymem/#files ) (download the source Pymem-***.tar.gz file)
2. Inside the archive you should find "pymem" module folder (it should have __init__.py file inside of it!)
3. Copy the folder into the folder where blender stores its modules. The path by default for blender 2.93 is `C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages`
4. After restarting blender, the add-on should work. If not, contact me!

**Comment by ShadowLuigi** [comment]
Been having this same issue when trying to install this

**Comment by ShadowLuigi** [comment]
thankfully this fixed my issues

**Comment by WeaselOnaStick** [comment]
The module has been excluded and is now distributed as a stand-alone blender add-on. Github page has same instructions for installing pymem which sadly can't be automated.
https://github.com/WeaselOnaStick/SharMemIO
